version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: climateapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  climate-backend:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    depends_on:
      - db

volumes:
  pgdata:
